version: "3.7"
services:

  backend:
    build: ./app
    command: ["/app/tools/run.sh"]
    volumes:
      - static_volume:/app/staticfiles
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "password"
      ADMIN_EMAIL: "admin@example.com"
      DATABASE_URL: "mysql://root:password@mysql:3306/db"
      ALLOW_SIGNUP: "False"
      DEBUG: "False"
    depends_on:
      - mysql
    networks:
      - network-backend
      - network-frontend

  frontend:
    build: ./frontend
    volumes:
      - www:/app/dist

  nginx:
    build: ./nginx
    volumes:
      - www:/var/www/html:ro
      - static_volume:/static
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - network-frontend

#  postgres:
#    image: postgres:12.0-alpine
##    volumes:
##      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      POSTGRES_USER: "doccano"
#      POSTGRES_PASSWORD: "doccano"
#      POSTGRES_DB: "doccano"
#    networks:
#      - network-backend

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - network-backend
    volumes:
      - my-db:/var/lib/mysql


volumes:
  postgres_data:
  static_volume:
  www:
  my-db:

networks:
  network-backend:
  network-frontend:
